In [118]:
import pandas as pd
import seaborn as sns
import numpy as np 
from sklearn.model_selection import train_test_split

In [119]:
df = pd.read_csv("dataset.csv")
df

C:\Users\NITRO 5\AppData\Local\Temp\ipykernel_16740\3660594139.py:1: DtypeWarning: Columns (9,15,23,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("dataset.csv")


Known As  Full Name  Overall    Potential  \
L. Messi              Lionel Messi         91       91         54.0   
K. Benzema           Karim Benzema         91       91   64000000.0   
R. Lewandowski  Robert Lewandowski         91       91          NaN   
K. De Bruyne       Kevin De Bruyne         91       91  107500000.0   
K. Mbappé            Kylian Mbappé         91       95  190500000.0   
...                            ...        ...      ...          ...   
D. Collins          Darren Collins         47       56     110000.0   
Yang Dejiang          Dejiang Yang         47       57      90000.0   
L. Mullan              Liam Mullan         47       67     130000.0   
D. McCallion      Daithí McCallion         47       61     100000.0   
N. Rabha               Nabin Rabha         47       50      60000.0   

               Value(in Euro) Positions Played        Best Position  \
L. Messi               000000               RW                  CAM   
K. Benzema              CF,ST               CF               France   
R. Lewandowski             ST               ST               Poland   
K. De Bruyne           CM,CAM               CM              Belgium   
K. Mbappé               ST,LW               ST               France   
...                       ...              ...                  ...   
D. Collins              ST,RM              CAM  Republic of Ireland   
Yang Dejiang              CDM              CDM             China PR   
L. Mullan                  CM               RM     Northern Ireland   
D. McCallion               CB               CB  Republic of Ireland   
N. Rabha                   LB               LB                India   

                                                     Nationality  \
L. Messi                                               Argentina   
K. Benzema      https://cdn.sofifa.net/players/165/153/23_60.png   
R. Lewandowski  https://cdn.sofifa.net/players/188/545/23_60.png   
K. De Bruyne    https://cdn.sofifa.net/players/192/985/23_60.png   
K. Mbappé       https://cdn.sofifa.net/players/231/747/23_60.png   
...                                                          ...   
D. Collins      https://cdn.sofifa.net/players/243/725/23_60.png   
Yang Dejiang    https://cdn.sofifa.net/players/261/933/23_60.png   
L. Mullan       https://cdn.sofifa.net/players/267/823/23_60.png   
D. McCallion    https://cdn.sofifa.net/players/267/824/23_60.png   
N. Rabha        https://cdn.sofifa.net/players/261/424/23_60.png   

                                                      Image Link  Age  ...  \
L. Messi        https://cdn.sofifa.net/players/158/023/23_60.png   35  ...   
K. Benzema                                                    34  185  ...   
R. Lewandowski                                                33  185  ...   
K. De Bruyne                                                  31  181  ...   
K. Mbappé                                                     23  182  ...   
...                                                          ...  ...  ...   
D. Collins                                                    21  174  ...   
Yang Dejiang                                                  17  175  ...   
L. Mullan                                                     18  170  ...   
D. McCallion                                                  17  178  ...   
N. Rabha                                                      25  176  ...   

                LM Rating  CM Rating  RM Rating LWB Rating CDM Rating  \
L. Messi               91         88         91         67         66   
K. Benzema             84         89         67         67         67   
R. Lewandowski         83         86         67         69         67   
K. De Bruyne           91         91         82         82         82   
K. Mbappé              84         92         70         66         70   
...                   ...        ...        ...        ...        ...   
D. Collins             44         50         41        

In [120]:
df.isna().sum()

Known As              0
Full Name             0
Overall               0
Potential             1
Value(in Euro)        0
                  ...  
RWB Rating            0
LB Rating             0
CB Rating             0
RB Rating             1
GK Rating         18538
Length: 89, dtype: int64

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18539 entries, L. Messi to N. Rabha
Data columns (total 89 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Known As                     18539 non-null  object 
 1   Full Name                    18539 non-null  int64  
 2   Overall                      18539 non-null  int64  
 3   Potential                    18538 non-null  float64
 4   Value(in Euro)               18539 non-null  object 
 5   Positions Played             18539 non-null  object 
 6   Best Position                18539 non-null  object 
 7   Nationality                  18539 non-null  object 
 8   Image Link                   18539 non-null  object 
 9   Age                          18539 non-null  int64  
 10  Height(in cm)                18539 non-null  int64  
 11  Weight(in kg)                18539 non-null  int64  
 12  TotalStats                   18539 non-null  int64  
 13  BaseStats  

## Training set 70 : testing set 30

In [122]:
X = df.iloc[:,:-1] 
Y = df.iloc[:,-1] 


In [123]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [124]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", X_test.shape)

Dimensi X_train :  (12977, 88)
Dimensi X_train :  (5562, 88)
Dimensi y_train :  (12977,)
Dimensi y_test :  (5562, 88)


## Normalisasi

In [125]:
from sklearn.preprocessing import MinMaxScaler

In [126]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['Overall','Potential','Age']])

In [127]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head(6)

0             1         2
0  0.914894  2.834646e-07  0.000000
1  0.914894  3.359580e-01  0.877193
2  0.914894           NaN  0.877193
3  0.914894  5.643045e-01  0.853801
4  1.000000  1.000000e+00  0.859649
5  0.893617  6.062992e-01  0.818713

## Standarisasi

In [128]:
from sklearn.preprocessing import StandardScaler

In [129]:
ss = StandardScaler()
data = np.asarray(df[['Overall','Potential','Age']])
Scaled = ss.fit_transform(data)

In [130]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))

print("\n Nilai Data setelah scaling : ") 
print(Scaled) 
print("Nilai standar deviasi: ", np.std(Scaled)) 

Nilai Data Sebelum scaling : 
[[9.10e+01 5.40e+01 3.50e+01]
 [9.10e+01 6.40e+07 1.85e+02]
 [9.10e+01      nan 1.85e+02]
 ...
 [6.70e+01 1.30e+05 1.70e+02]
 [6.10e+01 1.00e+05 1.78e+02]
 [5.00e+01 6.00e+04 1.76e+02]]
Nilai standar deviasi:  nan

 Nilai Data setelah scaling : 
[[  3.22691791  -0.37725475 -21.1120053 ]
 [  3.22691791   8.04090674   0.49794943]
 [  3.22691791          nan   0.49794943]
 ...
 [ -0.64861336  -0.36016244  -1.66304604]
 [ -1.61749618  -0.36410846  -0.51051512]
 [ -3.39378135  -0.36936982  -0.79864785]]
Nilai standar deviasi:  nan


## Data Cleaning

In [131]:
from sklearn.impute import SimpleImputer

In [132]:
df.isna().sum()

Known As              0
Full Name             0
Overall               0
Potential             1
Value(in Euro)        0
                  ...  
RWB Rating            0
LB Rating             0
CB Rating             0
RB Rating             1
GK Rating         18538
Length: 89, dtype: int64

## Ubah nilai null yang memiliki tipe data kategorikal

In [133]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["Potential"] = imputer.fit_transform(df[["Potential"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
Known As              0
Full Name             0
Overall               0
Potential             0
Value(in Euro)        0
                  ...  
RWB Rating            0
LB Rating             0
CB Rating             0
RB Rating             1
GK Rating         18538
Length: 89, dtype: int64


## Ubah nilai null yang memiliki tipe data desimal

In [134]:
imputer = SimpleImputer(strategy = 'mean')
df["GK Rating"] = imputer.fit_transform(df[["GK Rating"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
Known As          0
Full Name         0
Overall           0
Potential         0
Value(in Euro)    0
                 ..
RWB Rating        0
LB Rating         0
CB Rating         0
RB Rating         1
GK Rating         0
Length: 89, dtype: int64


## Ubah nilai null yang memiliki tipe data bilang bulat

In [135]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["RB Rating"] = imputer.fit_transform(df[["RB Rating"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
Known As          0
Full Name         0
Overall           0
Potential         0
Value(in Euro)    0
                 ..
RWB Rating        0
LB Rating         0
CB Rating         0
RB Rating         0
GK Rating         0
Length: 89, dtype: int64


## Ubah tipe data angka menjadi kategorikal

In [136]:
from sklearn.preprocessing import OrdinalEncoder 

In [137]:
encoder = OrdinalEncoder() 
df["LB Rating"] = encoder.fit_transform(df[["LB Rating"]]) 
df.head()

Known As  Full Name  Overall    Potential  \
L. Messi              Lionel Messi         91       91         54.0   
K. Benzema           Karim Benzema         91       91   64000000.0   
R. Lewandowski  Robert Lewandowski         91       91    1100000.0   
K. De Bruyne       Kevin De Bruyne         91       91  107500000.0   
K. Mbappé            Kylian Mbappé         91       95  190500000.0   

               Value(in Euro) Positions Played Best Position  \
L. Messi               000000               RW           CAM   
K. Benzema              CF,ST               CF        France   
R. Lewandowski             ST               ST        Poland   
K. De Bruyne           CM,CAM               CM       Belgium   
K. Mbappé               ST,LW               ST        France   

                                                     Nationality  \
L. Messi                                               Argentina   
K. Benzema      https://cdn.sofifa.net/players/165/153/23_60.png   
R. Lewandowski  https://cdn.sofifa.net/players/188/545/23_60.png   
K. De Bruyne    https://cdn.sofifa.net/players/192/985/23_60.png   
K. Mbappé       https://cdn.sofifa.net/players/231/747/23_60.png   

                                                      Image Link  Age  ...  \
L. Messi        https://cdn.sofifa.net/players/158/023/23_60.png   35  ...   
K. Benzema                                                    34  185  ...   
R. Lewandowski                                                33  185  ...   
K. De Bruyne                                                  31  181  ...   
K. Mbappé                                                     23  182  ...   

                LM Rating  CM Rating  RM Rating LWB Rating CDM Rating  \
L. Messi               91         88         91         67         66   
K. Benzema             84         89         67         67         67   
R. Lewandowski         83         86         67         69         67   
K. De Bruyne           91         91         82         82         82   
K. Mbappé              84         92         70         66         70   

                RWB Rating LB Rating CB Rating RB Rating  GK Rating  
L. Messi                67      44.0        53      62.0       22.0  
K. Benzema              63      40.0        63      21.0       22.0  
R. Lewandowski          64      45.0        64      18.0       22.0  
K. De Bruyne            78      54.0        78      24.0       22.0  
K. Mbappé               66      39.0        66      21.0       22.0  

[5 rows x 89 columns]

## One Hot Encoding

In [156]:
from sklearn.preprocessing import OneHotEncoder 

In [158]:
encoder = OneHotEncoder(sparse=False) 
PotentialEnc = encoder.fit_transform(df[["Potential"]]) 
PotentialEnc = pd.DataFrame(PotentialEnc) 
df = df.join(PotentialEnc) 
df 

TypeError: '<' not supported between instances of 'str' and 'int'

## Data Duplikat (Sama)

In [141]:
df[df.duplicated()]

Known As  Full Name  Overall   Potential  \
Aihen Muñoz        Aihen Muñoz Capellán         75       80   8000000.0   
A. Hickey                  Aaron Hickey         75       85  12000000.0   
J. Graterol               Joel Graterol         75       81   7000000.0   
K. Adeyemi                Karim Adeyemi         75       87  13500000.0   
S. Bornauw           Sebastiaan Bornauw         75       81   8000000.0   
...                                 ...        ...      ...         ...   
Jean         Jean Paulo Fernandes Filho         75       78   5500000.0   
L. Tawamba              Léandre Tawamba         75       75   4600000.0   
S. Berge                   Sander Berge         75       81   8000000.0   
A. Varela                   Alan Varela         75       85  11500000.0   
J. Gallardo              Jesús Gallardo         75       75         0.0   

            Value(in Euro) Positions Played Best Position  \
Aihen Muñoz             LB               LB         Spain   
A. Hickey        RB,LB,LWB               RB      Scotland   
J. Graterol             GK               GK     Venezuela   
K. Adeyemi              ST               ST       Germany   
S. Bornauw              CB               CB       Belgium   
...                    ...              ...           ...   
Jean                    GK               GK        Brazil   
L. Tawamba              ST               ST      Cameroon   
S. Berge            CDM,CM               CB        Norway   
A. Varela           CDM,CM              CDM     Argentina   
J. Gallardo       LB,LM,LW               LB        Mexico   

                                                  Nationality Image Link  Age  \
Aihen Muñoz  https://cdn.sofifa.net/players/246/748/23_60.png         24  175   
A. Hickey    https://cdn.sofifa.net/players/248/808/23_60.png         20  175   
J. Graterol  https://cdn.sofifa.net/players/250/842/23_60.png         25  176   
K. Adeyemi   https://cdn.sofifa.net/players/251/852/23_60.png         20  177   
S. Bornauw   https://cdn.sofifa.net/players/242/663/23_60.png         23  191   
...                                                       ...        ...  ...   
Jean         https://cdn.sofifa.net/players/234/999/23_60.png         26  188   
L. Tawamba   https://cdn.sofifa.net/players/244/727/23_60.png         32  189   
S. Berge     https://cdn.sofifa.net/players/228/092/23_60.png         24  195   
A. Varela    https://cdn.sofifa.net/players/260/599/23_60.png         20  177   
J. Gallardo  https://cdn.sofifa.net/players/226/045/23_60.png         27  176   

             ...  LM Rating  CM Rating  RM Rating LWB Rating CDM Rating  \
Aihen Muñoz  ...         73         74         75         74         75   
A. Hickey    ...         72         73         75         72         75   
J. Graterol  ...         29         25         22         25         22   
K. Adeyemi   ...         68         76         56         51         56   
S. Bornauw   ...         63         62         70         72         70   
...          ...        ...        ...        ...        ...        ...   
Jean         ...         28         26         23         27         23   
L. Tawamba   ...         65         69         49         50         49   
S. Berge     ...         75         73         74         76         74   
A. Varela    ...         75         72         75         76         75   
J. Gallardo  ...         73         75         75         72         75   

             RWB Rating LB Rating CB Rating RB Rating  GK Rating  
Aihen Muñoz          75      55.0        75      21.0       22.0  
A. Hickey            75      50.0        75      19.0       22.0  
J. Graterol          22       6.0        22      76.0       22.0  
K. Adeyemi           53      27.0        53      19.0       22.0  
S. Bornauw           73      59.0        73      18.0       22.0  
...                 ...       ...       ...       ...        ...  
Jean                 23       8.0        23      76.0 

In [142]:
df.drop_duplicates(inplace=True)

In [144]:
print("Jumlah Nilai Duplikat:",df.duplicated().sum())

Jumlah Nilai Duplikat: 0
